In [8]:
from tensorflow.keras.preprocessing.text import one_hot

sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [9]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [10]:
#define vocabulary size
voc_size=10000

In [11]:
#one hote representation
one_hot_repr=[one_hot(words,voc_size) for words in sent]
one_hot_repr

[[9286, 5179, 5331, 1207],
 [9286, 5179, 5331, 4602],
 [9286, 8979, 5331, 5902],
 [5503, 7616, 7496, 3975, 8070],
 [5503, 7616, 7496, 3975, 4777],
 [5379, 9286, 6152, 5331, 112],
 [339, 4079, 3447, 3975]]

In [12]:
import numpy as np


In [13]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

import numpy as np


sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 9286 5179 5331 1207]
 [   0    0    0    0 9286 5179 5331 4602]
 [   0    0    0    0 9286 8979 5331 5902]
 [   0    0    0 5503 7616 7496 3975 8070]
 [   0    0    0 5503 7616 7496 3975 4777]
 [   0    0    0 5379 9286 6152 5331  112]
 [   0    0    0    0  339 4079 3447 3975]]


In [14]:
#feature representation

dim=10



In [15]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [16]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [17]:
model.predict(embedded_docs)


1/1 [==============================] - 0s 76ms/step


array([[[ 0.01837888,  0.0182204 ,  0.00286387,  0.03799507,
         -0.00242791,  0.02793414, -0.02138736,  0.04963893,
         -0.01607205, -0.02508842],
        [ 0.01837888,  0.0182204 ,  0.00286387,  0.03799507,
         -0.00242791,  0.02793414, -0.02138736,  0.04963893,
         -0.01607205, -0.02508842],
        [ 0.01837888,  0.0182204 ,  0.00286387,  0.03799507,
         -0.00242791,  0.02793414, -0.02138736,  0.04963893,
         -0.01607205, -0.02508842],
        [ 0.01837888,  0.0182204 ,  0.00286387,  0.03799507,
         -0.00242791,  0.02793414, -0.02138736,  0.04963893,
         -0.01607205, -0.02508842],
        [ 0.03561353, -0.01982956, -0.01658747,  0.04211711,
         -0.00141941,  0.000669  , -0.04431346,  0.00527833,
          0.01889271,  0.03180758],
        [ 0.0121348 ,  0.02993735,  0.04888116,  0.03352639,
          0.02358631, -0.02478004, -0.00166623, -0.02364823,
         -0.0101607 , -0.00780518],
        [-0.02901602,  0.00653409, -0.02337083,  0.0